name: Moar
main: com.hexbit.moar.Moar
version: 0.1

commands:
    moar:
        description: Gives the player more of the currently held block
        usage: /moar <amount>
    moar:
        description: Gives the player more of the specified block
        usage: /moar <id> <amount>
    m:
        description: Tops off the currently held stack
        usage: /m
